package com.hyf.backend.coupon.template.dataobject;

import com.hyf.backend.common.domain.DateAndAuthorTraceableDO;
import com.hyf.backend.coupon.template.constant.CouponDiscountCategoryEnum;
import com.hyf.backend.coupon.template.constant.CouponTemplateExpirationEnum;
import java.util.Date;

public class CouponTemplateDO extends DateAndAuthorTraceableDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.is_available
     *
     * @mbg.generated
     */
    private Boolean isAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.is_expired
     *
     * @mbg.generated
     */
    private Boolean isExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.discount_category
     *
     * @mbg.generated
     */
    private CouponDiscountCategoryEnum discountCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.coupon_count
     *
     * @mbg.generated
     */
    private Integer couponCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.template_key
     *
     * @mbg.generated
     */
    private String templateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.dispatch_users
     *
     * @mbg.generated
     */
    private String dispatchUsers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.expiration_code
     *
     * @mbg.generated
     */
    private CouponTemplateExpirationEnum expirationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.expiration_gap
     *
     * @mbg.generated
     */
    private Integer expirationGap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.expiration_deadline
     *
     * @mbg.generated
     */
    private Date expirationDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.manjian_quota
     *
     * @mbg.generated
     */
    private Integer manjianQuota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.lijian_quota
     *
     * @mbg.generated
     */
    private Integer lijianQuota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.zhekou_quota
     *
     * @mbg.generated
     */
    private Integer zhekouQuota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.discount_base
     *
     * @mbg.generated
     */
    private Integer discountBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.each_get_limitation
     *
     * @mbg.generated
     */
    private Integer eachGetLimitation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.goods_type_limitation
     *
     * @mbg.generated
     */
    private String goodsTypeLimitation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_coupon_template.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.id
     *
     * @return the value of sales_coupon_template.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.id
     *
     * @param id the value for sales_coupon_template.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.is_available
     *
     * @return the value of sales_coupon_template.is_available
     *
     * @mbg.generated
     */
    public Boolean getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.is_available
     *
     * @param isAvailable the value for sales_coupon_template.is_available
     *
     * @mbg.generated
     */
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.is_expired
     *
     * @return the value of sales_coupon_template.is_expired
     *
     * @mbg.generated
     */
    public Boolean getIsExpired() {
        return isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.is_expired
     *
     * @param isExpired the value for sales_coupon_template.is_expired
     *
     * @mbg.generated
     */
    public void setIsExpired(Boolean isExpired) {
        this.isExpired = isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.title
     *
     * @return the value of sales_coupon_template.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.title
     *
     * @param title the value for sales_coupon_template.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.logo
     *
     * @return the value of sales_coupon_template.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.logo
     *
     * @param logo the value for sales_coupon_template.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.discount_category
     *
     * @return the value of sales_coupon_template.discount_category
     *
     * @mbg.generated
     */
    public CouponDiscountCategoryEnum getDiscountCategory() {
        return discountCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.discount_category
     *
     * @param discountCategory the value for sales_coupon_template.discount_category
     *
     * @mbg.generated
     */
    public void setDiscountCategory(CouponDiscountCategoryEnum discountCategory) {
        this.discountCategory = discountCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.coupon_count
     *
     * @return the value of sales_coupon_template.coupon_count
     *
     * @mbg.generated
     */
    public Integer getCouponCount() {
        return couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.coupon_count
     *
     * @param couponCount the value for sales_coupon_template.coupon_count
     *
     * @mbg.generated
     */
    public void setCouponCount(Integer couponCount) {
        this.couponCount = couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.template_key
     *
     * @return the value of sales_coupon_template.template_key
     *
     * @mbg.generated
     */
    public String getTemplateKey() {
        return templateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.template_key
     *
     * @param templateKey the value for sales_coupon_template.template_key
     *
     * @mbg.generated
     */
    public void setTemplateKey(String templateKey) {
        this.templateKey = templateKey == null ? null : templateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.dispatch_users
     *
     * @return the value of sales_coupon_template.dispatch_users
     *
     * @mbg.generated
     */
    public String getDispatchUsers() {
        return dispatchUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.dispatch_users
     *
     * @param dispatchUsers the value for sales_coupon_template.dispatch_users
     *
     * @mbg.generated
     */
    public void setDispatchUsers(String dispatchUsers) {
        this.dispatchUsers = dispatchUsers == null ? null : dispatchUsers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.expiration_code
     *
     * @return the value of sales_coupon_template.expiration_code
     *
     * @mbg.generated
     */
    public CouponTemplateExpirationEnum getExpirationCode() {
        return expirationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.expiration_code
     *
     * @param expirationCode the value for sales_coupon_template.expiration_code
     *
     * @mbg.generated
     */
    public void setExpirationCode(CouponTemplateExpirationEnum expirationCode) {
        this.expirationCode = expirationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.expiration_gap
     *
     * @return the value of sales_coupon_template.expiration_gap
     *
     * @mbg.generated
     */
    public Integer getExpirationGap() {
        return expirationGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.expiration_gap
     *
     * @param expirationGap the value for sales_coupon_template.expiration_gap
     *
     * @mbg.generated
     */
    public void setExpirationGap(Integer expirationGap) {
        this.expirationGap = expirationGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.expiration_deadline
     *
     * @return the value of sales_coupon_template.expiration_deadline
     *
     * @mbg.generated
     */
    public Date getExpirationDeadline() {
        return expirationDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.expiration_deadline
     *
     * @param expirationDeadline the value for sales_coupon_template.expiration_deadline
     *
     * @mbg.generated
     */
    public void setExpirationDeadline(Date expirationDeadline) {
        this.expirationDeadline = expirationDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.manjian_quota
     *
     * @return the value of sales_coupon_template.manjian_quota
     *
     * @mbg.generated
     */
    public Integer getManjianQuota() {
        return manjianQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.manjian_quota
     *
     * @param manjianQuota the value for sales_coupon_template.manjian_quota
     *
     * @mbg.generated
     */
    public void setManjianQuota(Integer manjianQuota) {
        this.manjianQuota = manjianQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.lijian_quota
     *
     * @return the value of sales_coupon_template.lijian_quota
     *
     * @mbg.generated
     */
    public Integer getLijianQuota() {
        return lijianQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.lijian_quota
     *
     * @param lijianQuota the value for sales_coupon_template.lijian_quota
     *
     * @mbg.generated
     */
    public void setLijianQuota(Integer lijianQuota) {
        this.lijianQuota = lijianQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.zhekou_quota
     *
     * @return the value of sales_coupon_template.zhekou_quota
     *
     * @mbg.generated
     */
    public Integer getZhekouQuota() {
        return zhekouQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.zhekou_quota
     *
     * @param zhekouQuota the value for sales_coupon_template.zhekou_quota
     *
     * @mbg.generated
     */
    public void setZhekouQuota(Integer zhekouQuota) {
        this.zhekouQuota = zhekouQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.discount_base
     *
     * @return the value of sales_coupon_template.discount_base
     *
     * @mbg.generated
     */
    public Integer getDiscountBase() {
        return discountBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.discount_base
     *
     * @param discountBase the value for sales_coupon_template.discount_base
     *
     * @mbg.generated
     */
    public void setDiscountBase(Integer discountBase) {
        this.discountBase = discountBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.each_get_limitation
     *
     * @return the value of sales_coupon_template.each_get_limitation
     *
     * @mbg.generated
     */
    public Integer getEachGetLimitation() {
        return eachGetLimitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.each_get_limitation
     *
     * @param eachGetLimitation the value for sales_coupon_template.each_get_limitation
     *
     * @mbg.generated
     */
    public void setEachGetLimitation(Integer eachGetLimitation) {
        this.eachGetLimitation = eachGetLimitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.goods_type_limitation
     *
     * @return the value of sales_coupon_template.goods_type_limitation
     *
     * @mbg.generated
     */
    public String getGoodsTypeLimitation() {
        return goodsTypeLimitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.goods_type_limitation
     *
     * @param goodsTypeLimitation the value for sales_coupon_template.goods_type_limitation
     *
     * @mbg.generated
     */
    public void setGoodsTypeLimitation(String goodsTypeLimitation) {
        this.goodsTypeLimitation = goodsTypeLimitation == null ? null : goodsTypeLimitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.weight
     *
     * @return the value of sales_coupon_template.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.weight
     *
     * @param weight the value for sales_coupon_template.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.create_user
     *
     * @return the value of sales_coupon_template.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.create_user
     *
     * @param createUser the value for sales_coupon_template.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.update_user
     *
     * @return the value of sales_coupon_template.update_user
     *
     * @mbg.generated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.update_user
     *
     * @param updateUser the value for sales_coupon_template.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.create_time
     *
     * @return the value of sales_coupon_template.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.create_time
     *
     * @param createTime the value for sales_coupon_template.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_coupon_template.update_time
     *
     * @return the value of sales_coupon_template.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_coupon_template.update_time
     *
     * @param updateTime the value for sales_coupon_template.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}