server:
  port: 8201
  servlet:
    context-path: /user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:33061/coupon?autoReconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: gdhuyufei
    filters: log4j,wall,mergeStat
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

#logging:
#  config: classpath:logback1.xml
feign:
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 5000