spring:
  application:
    name: zuul-gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: gdhuyufei
    filters: log4j,wall,mergeStat
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

server:
  port: 9090
zuul:
  routes:
    template-service:
      path: /template-service/**
      serviceId: template-service
      strip-prefix: false
      sensitiveHeaders:
    user-service:
      path: /user-service/**
      serviceId: user-service
#     false时候前缀不会被移除
      strip-refix: false
      sensitiveHeaders:
  prefix: /api
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    #让每一个路由在单独的线程池中隔离
#  使用线程池的隔离方式
###Hystrix的超时时间要大于Ribbon否则还没到Ribbon重试，就被Hystrix给熔断了
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
          strategy: thread
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 800

###全局的Ribbon配置
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 10000
  ServerListRefreshInterval: 2000
##每个路由服务使用单独的负载均衡策略
#template-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.hyf.backend.zuul.ribbon.MyRuleLoadBalancer
#    ReadTimeout: 2000
#    ConnectTimeout: 1000
#    MaxAutoRetries: 1
logging:
  level:
    com.netflix: debug
#    MaxAutoRetriesNextServer: 1