mybatis-plus:
  #  mapper-locations: classpath*:mapper/*.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: source-soource
  datasource:
    url: jdbc:mysql://127.0.0.1:33061/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: huyufei
    password: gdhuyufei
    filters: log4j,wall,mergeStat
    type: com.zaxxer.hikari.HikariDataSource